/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import at.ac.tuwien.big.views.view.services.ViewGrammarAccess;

public class ViewParser extends AbstractContentAssistParser {
	
	@Inject
	private ViewGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected at.ac.tuwien.big.views.view.ui.contentassist.antlr.internal.InternalViewParser createParser() {
		at.ac.tuwien.big.views.view.ui.contentassist.antlr.internal.InternalViewParser result = new at.ac.tuwien.big.views.view.ui.contentassist.antlr.internal.InternalViewParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getViewAccess().getAlternatives(), "rule__View__Alternatives");
					put(grammarAccess.getClassOperationViewAccess().getAlternatives(), "rule__ClassOperationView__Alternatives");
					put(grammarAccess.getConditionalElementAccess().getAlternatives(), "rule__ConditionalElement__Alternatives");
					put(grammarAccess.getViewElementAccess().getAlternatives_0(), "rule__ViewElement__Alternatives_0");
					put(grammarAccess.getAssociationElementAccess().getAlternatives(), "rule__AssociationElement__Alternatives");
					put(grammarAccess.getTableAccess().getAlternatives_6(), "rule__Table__Alternatives_6");
					put(grammarAccess.getPropertyElementAccess().getAlternatives(), "rule__PropertyElement__Alternatives");
					put(grammarAccess.getSelectionItemAccess().getAlternatives(), "rule__SelectionItem__Alternatives");
					put(grammarAccess.getLinkableElementAccess().getAlternatives(), "rule__LinkableElement__Alternatives");
					put(grammarAccess.getLayoutableElementAccess().getAlternatives(), "rule__LayoutableElement__Alternatives");
					put(grammarAccess.getVisibilityConditionAccess().getAlternatives(), "rule__VisibilityCondition__Alternatives");
					put(grammarAccess.getLayoutStyleAccess().getAlternatives(), "rule__LayoutStyle__Alternatives");
					put(grammarAccess.getVisibilityConditionTypeAccess().getAlternatives(), "rule__VisibilityConditionType__Alternatives");
					put(grammarAccess.getCompositeConditionTypeAccess().getAlternatives(), "rule__CompositeConditionType__Alternatives");
					put(grammarAccess.getComparisonConditionTypeAccess().getAlternatives(), "rule__ComparisonConditionType__Alternatives");
					put(grammarAccess.getViewModelAccess().getGroup(), "rule__ViewModel__Group__0");
					put(grammarAccess.getViewGroupAccess().getGroup(), "rule__ViewGroup__Group__0");
					put(grammarAccess.getViewGroupAccess().getGroup_4(), "rule__ViewGroup__Group_4__0");
					put(grammarAccess.getViewGroupAccess().getGroup_4_1(), "rule__ViewGroup__Group_4_1__0");
					put(grammarAccess.getClassIndexViewAccess().getGroup(), "rule__ClassIndexView__Group__0");
					put(grammarAccess.getClassIndexViewAccess().getGroup_7(), "rule__ClassIndexView__Group_7__0");
					put(grammarAccess.getClassIndexViewAccess().getGroup_8(), "rule__ClassIndexView__Group_8__0");
					put(grammarAccess.getClassIndexViewAccess().getGroup_8_1(), "rule__ClassIndexView__Group_8_1__0");
					put(grammarAccess.getCreateViewAccess().getGroup(), "rule__CreateView__Group__0");
					put(grammarAccess.getCreateViewAccess().getGroup_8(), "rule__CreateView__Group_8__0");
					put(grammarAccess.getCreateViewAccess().getGroup_9(), "rule__CreateView__Group_9__0");
					put(grammarAccess.getCreateViewAccess().getGroup_9_1(), "rule__CreateView__Group_9_1__0");
					put(grammarAccess.getReadViewAccess().getGroup(), "rule__ReadView__Group__0");
					put(grammarAccess.getReadViewAccess().getGroup_8(), "rule__ReadView__Group_8__0");
					put(grammarAccess.getReadViewAccess().getGroup_9(), "rule__ReadView__Group_9__0");
					put(grammarAccess.getReadViewAccess().getGroup_9_1(), "rule__ReadView__Group_9_1__0");
					put(grammarAccess.getUpdateViewAccess().getGroup(), "rule__UpdateView__Group__0");
					put(grammarAccess.getUpdateViewAccess().getGroup_8(), "rule__UpdateView__Group_8__0");
					put(grammarAccess.getUpdateViewAccess().getGroup_9(), "rule__UpdateView__Group_9__0");
					put(grammarAccess.getUpdateViewAccess().getGroup_9_1(), "rule__UpdateView__Group_9_1__0");
					put(grammarAccess.getDeleteViewAccess().getGroup(), "rule__DeleteView__Group__0");
					put(grammarAccess.getDeleteViewAccess().getGroup_8(), "rule__DeleteView__Group_8__0");
					put(grammarAccess.getDeleteViewAccess().getGroup_9(), "rule__DeleteView__Group_9__0");
					put(grammarAccess.getDeleteViewAccess().getGroup_9_1(), "rule__DeleteView__Group_9_1__0");
					put(grammarAccess.getElementGroupAccess().getGroup(), "rule__ElementGroup__Group__0");
					put(grammarAccess.getElementGroupAccess().getGroup_4(), "rule__ElementGroup__Group_4__0");
					put(grammarAccess.getElementGroupAccess().getGroup_4_1(), "rule__ElementGroup__Group_4_1__0");
					put(grammarAccess.getElementGroupAccess().getGroup_6(), "rule__ElementGroup__Group_6__0");
					put(grammarAccess.getViewElementAccess().getGroup(), "rule__ViewElement__Group__0");
					put(grammarAccess.getViewElementAccess().getGroup_1(), "rule__ViewElement__Group_1__0");
					put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
					put(grammarAccess.getListAccess().getGroup_6(), "rule__List__Group_6__0");
					put(grammarAccess.getListAccess().getGroup_6_1(), "rule__List__Group_6_1__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getTableAccess().getGroup_6_0(), "rule__Table__Group_6_0__0");
					put(grammarAccess.getTableAccess().getGroup_6_0_1(), "rule__Table__Group_6_0_1__0");
					put(grammarAccess.getTableAccess().getGroup_6_1(), "rule__Table__Group_6_1__0");
					put(grammarAccess.getTableAccess().getGroup_6_1_0(), "rule__Table__Group_6_1_0__0");
					put(grammarAccess.getTableAccess().getGroup_6_1_1(), "rule__Table__Group_6_1_1__0");
					put(grammarAccess.getTableAccess().getGroup_6_1_1_1(), "rule__Table__Group_6_1_1_1__0");
					put(grammarAccess.getTableAccess().getGroup_6_2(), "rule__Table__Group_6_2__0");
					put(grammarAccess.getTableAccess().getGroup_6_2_1(), "rule__Table__Group_6_2_1__0");
					put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
					put(grammarAccess.getDateTimePickerAccess().getGroup(), "rule__DateTimePicker__Group__0");
					put(grammarAccess.getDateTimePickerAccess().getGroup_3(), "rule__DateTimePicker__Group_3__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getTextAccess().getGroup_4(), "rule__Text__Group_4__0");
					put(grammarAccess.getSelectionAccess().getGroup(), "rule__Selection__Group__0");
					put(grammarAccess.getSelectionAccess().getGroup_6(), "rule__Selection__Group_6__0");
					put(grammarAccess.getSelectionAccess().getGroup_6_1(), "rule__Selection__Group_6_1__0");
					put(grammarAccess.getSelectionItemAccess().getGroup_1(), "rule__SelectionItem__Group_1__0");
					put(grammarAccess.getEnumerationLiteralItemAccess().getGroup(), "rule__EnumerationLiteralItem__Group__0");
					put(grammarAccess.getLinkableElementAccess().getGroup_1(), "rule__LinkableElement__Group_1__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getCompositeConditionAccess().getGroup(), "rule__CompositeCondition__Group__0");
					put(grammarAccess.getCompositeConditionAccess().getGroup_4(), "rule__CompositeCondition__Group_4__0");
					put(grammarAccess.getComparisonConditionAccess().getGroup(), "rule__ComparisonCondition__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getViewModelAccess().getViewGroupsAssignment_0(), "rule__ViewModel__ViewGroupsAssignment_0");
					put(grammarAccess.getViewModelAccess().getViewGroupsAssignment_1(), "rule__ViewModel__ViewGroupsAssignment_1");
					put(grammarAccess.getViewGroupAccess().getWelcomeViewGroupAssignment_0(), "rule__ViewGroup__WelcomeViewGroupAssignment_0");
					put(grammarAccess.getViewGroupAccess().getNameAssignment_2(), "rule__ViewGroup__NameAssignment_2");
					put(grammarAccess.getViewGroupAccess().getViewsAssignment_4_0(), "rule__ViewGroup__ViewsAssignment_4_0");
					put(grammarAccess.getViewGroupAccess().getViewsAssignment_4_1_1(), "rule__ViewGroup__ViewsAssignment_4_1_1");
					put(grammarAccess.getClassIndexViewAccess().getStartViewAssignment_0(), "rule__ClassIndexView__StartViewAssignment_0");
					put(grammarAccess.getClassIndexViewAccess().getNameAssignment_2(), "rule__ClassIndexView__NameAssignment_2");
					put(grammarAccess.getClassIndexViewAccess().getHeaderAssignment_3(), "rule__ClassIndexView__HeaderAssignment_3");
					put(grammarAccess.getClassIndexViewAccess().getClassAssignment_5(), "rule__ClassIndexView__ClassAssignment_5");
					put(grammarAccess.getClassIndexViewAccess().getDescriptionAssignment_7_1(), "rule__ClassIndexView__DescriptionAssignment_7_1");
					put(grammarAccess.getClassIndexViewAccess().getLinkAssignment_8_0(), "rule__ClassIndexView__LinkAssignment_8_0");
					put(grammarAccess.getClassIndexViewAccess().getLinkAssignment_8_1_1(), "rule__ClassIndexView__LinkAssignment_8_1_1");
					put(grammarAccess.getCreateViewAccess().getLayoutAssignment_0(), "rule__CreateView__LayoutAssignment_0");
					put(grammarAccess.getCreateViewAccess().getStartViewAssignment_1(), "rule__CreateView__StartViewAssignment_1");
					put(grammarAccess.getCreateViewAccess().getNameAssignment_3(), "rule__CreateView__NameAssignment_3");
					put(grammarAccess.getCreateViewAccess().getHeaderAssignment_4(), "rule__CreateView__HeaderAssignment_4");
					put(grammarAccess.getCreateViewAccess().getClassAssignment_6(), "rule__CreateView__ClassAssignment_6");
					put(grammarAccess.getCreateViewAccess().getDescriptionAssignment_8_1(), "rule__CreateView__DescriptionAssignment_8_1");
					put(grammarAccess.getCreateViewAccess().getElementGroupsAssignment_9_0(), "rule__CreateView__ElementGroupsAssignment_9_0");
					put(grammarAccess.getCreateViewAccess().getElementGroupsAssignment_9_1_1(), "rule__CreateView__ElementGroupsAssignment_9_1_1");
					put(grammarAccess.getReadViewAccess().getLayoutAssignment_0(), "rule__ReadView__LayoutAssignment_0");
					put(grammarAccess.getReadViewAccess().getStartViewAssignment_1(), "rule__ReadView__StartViewAssignment_1");
					put(grammarAccess.getReadViewAccess().getNameAssignment_3(), "rule__ReadView__NameAssignment_3");
					put(grammarAccess.getReadViewAccess().getHeaderAssignment_4(), "rule__ReadView__HeaderAssignment_4");
					put(grammarAccess.getReadViewAccess().getClassAssignment_6(), "rule__ReadView__ClassAssignment_6");
					put(grammarAccess.getReadViewAccess().getDescriptionAssignment_8_1(), "rule__ReadView__DescriptionAssignment_8_1");
					put(grammarAccess.getReadViewAccess().getElementGroupsAssignment_9_0(), "rule__ReadView__ElementGroupsAssignment_9_0");
					put(grammarAccess.getReadViewAccess().getElementGroupsAssignment_9_1_1(), "rule__ReadView__ElementGroupsAssignment_9_1_1");
					put(grammarAccess.getUpdateViewAccess().getLayoutAssignment_0(), "rule__UpdateView__LayoutAssignment_0");
					put(grammarAccess.getUpdateViewAccess().getStartViewAssignment_1(), "rule__UpdateView__StartViewAssignment_1");
					put(grammarAccess.getUpdateViewAccess().getNameAssignment_3(), "rule__UpdateView__NameAssignment_3");
					put(grammarAccess.getUpdateViewAccess().getHeaderAssignment_4(), "rule__UpdateView__HeaderAssignment_4");
					put(grammarAccess.getUpdateViewAccess().getClassAssignment_6(), "rule__UpdateView__ClassAssignment_6");
					put(grammarAccess.getUpdateViewAccess().getDescriptionAssignment_8_1(), "rule__UpdateView__DescriptionAssignment_8_1");
					put(grammarAccess.getUpdateViewAccess().getElementGroupsAssignment_9_0(), "rule__UpdateView__ElementGroupsAssignment_9_0");
					put(grammarAccess.getUpdateViewAccess().getElementGroupsAssignment_9_1_1(), "rule__UpdateView__ElementGroupsAssignment_9_1_1");
					put(grammarAccess.getDeleteViewAccess().getLayoutAssignment_0(), "rule__DeleteView__LayoutAssignment_0");
					put(grammarAccess.getDeleteViewAccess().getStartViewAssignment_1(), "rule__DeleteView__StartViewAssignment_1");
					put(grammarAccess.getDeleteViewAccess().getNameAssignment_3(), "rule__DeleteView__NameAssignment_3");
					put(grammarAccess.getDeleteViewAccess().getHeaderAssignment_4(), "rule__DeleteView__HeaderAssignment_4");
					put(grammarAccess.getDeleteViewAccess().getClassAssignment_6(), "rule__DeleteView__ClassAssignment_6");
					put(grammarAccess.getDeleteViewAccess().getDescriptionAssignment_8_1(), "rule__DeleteView__DescriptionAssignment_8_1");
					put(grammarAccess.getDeleteViewAccess().getElementGroupsAssignment_9_0(), "rule__DeleteView__ElementGroupsAssignment_9_0");
					put(grammarAccess.getDeleteViewAccess().getElementGroupsAssignment_9_1_1(), "rule__DeleteView__ElementGroupsAssignment_9_1_1");
					put(grammarAccess.getElementGroupAccess().getLayoutAssignment_0(), "rule__ElementGroup__LayoutAssignment_0");
					put(grammarAccess.getElementGroupAccess().getHeaderAssignment_2(), "rule__ElementGroup__HeaderAssignment_2");
					put(grammarAccess.getElementGroupAccess().getViewElementsAssignment_4_0(), "rule__ElementGroup__ViewElementsAssignment_4_0");
					put(grammarAccess.getElementGroupAccess().getViewElementsAssignment_4_1_1(), "rule__ElementGroup__ViewElementsAssignment_4_1_1");
					put(grammarAccess.getElementGroupAccess().getConditionAssignment_6_1(), "rule__ElementGroup__ConditionAssignment_6_1");
					put(grammarAccess.getViewElementAccess().getConditionAssignment_1_1(), "rule__ViewElement__ConditionAssignment_1_1");
					put(grammarAccess.getListAccess().getElementIDAssignment_1(), "rule__List__ElementIDAssignment_1");
					put(grammarAccess.getListAccess().getLabelAssignment_2(), "rule__List__LabelAssignment_2");
					put(grammarAccess.getListAccess().getAssociationAssignment_4(), "rule__List__AssociationAssignment_4");
					put(grammarAccess.getListAccess().getLinkAssignment_6_0(), "rule__List__LinkAssignment_6_0");
					put(grammarAccess.getListAccess().getLinkAssignment_6_1_1(), "rule__List__LinkAssignment_6_1_1");
					put(grammarAccess.getTableAccess().getElementIDAssignment_1(), "rule__Table__ElementIDAssignment_1");
					put(grammarAccess.getTableAccess().getLabelAssignment_2(), "rule__Table__LabelAssignment_2");
					put(grammarAccess.getTableAccess().getAssociationAssignment_4(), "rule__Table__AssociationAssignment_4");
					put(grammarAccess.getTableAccess().getLinkAssignment_6_0_0(), "rule__Table__LinkAssignment_6_0_0");
					put(grammarAccess.getTableAccess().getLinkAssignment_6_0_1_1(), "rule__Table__LinkAssignment_6_0_1_1");
					put(grammarAccess.getTableAccess().getLinkAssignment_6_1_0_0(), "rule__Table__LinkAssignment_6_1_0_0");
					put(grammarAccess.getTableAccess().getColumnsAssignment_6_1_1_0(), "rule__Table__ColumnsAssignment_6_1_1_0");
					put(grammarAccess.getTableAccess().getColumnsAssignment_6_1_1_1_1(), "rule__Table__ColumnsAssignment_6_1_1_1_1");
					put(grammarAccess.getTableAccess().getColumnsAssignment_6_2_0(), "rule__Table__ColumnsAssignment_6_2_0");
					put(grammarAccess.getTableAccess().getColumnsAssignment_6_2_1_1(), "rule__Table__ColumnsAssignment_6_2_1_1");
					put(grammarAccess.getColumnAccess().getElementIDAssignment_1(), "rule__Column__ElementIDAssignment_1");
					put(grammarAccess.getColumnAccess().getLabelAssignment_2(), "rule__Column__LabelAssignment_2");
					put(grammarAccess.getColumnAccess().getPropertyAssignment_4(), "rule__Column__PropertyAssignment_4");
					put(grammarAccess.getDateTimePickerAccess().getElementIDAssignment_1(), "rule__DateTimePicker__ElementIDAssignment_1");
					put(grammarAccess.getDateTimePickerAccess().getLabelAssignment_2(), "rule__DateTimePicker__LabelAssignment_2");
					put(grammarAccess.getDateTimePickerAccess().getFormatAssignment_3_1(), "rule__DateTimePicker__FormatAssignment_3_1");
					put(grammarAccess.getDateTimePickerAccess().getPropertyAssignment_5(), "rule__DateTimePicker__PropertyAssignment_5");
					put(grammarAccess.getTextAccess().getLongAssignment_0(), "rule__Text__LongAssignment_0");
					put(grammarAccess.getTextAccess().getElementIDAssignment_2(), "rule__Text__ElementIDAssignment_2");
					put(grammarAccess.getTextAccess().getLabelAssignment_3(), "rule__Text__LabelAssignment_3");
					put(grammarAccess.getTextAccess().getFormatAssignment_4_1(), "rule__Text__FormatAssignment_4_1");
					put(grammarAccess.getTextAccess().getPropertyAssignment_6(), "rule__Text__PropertyAssignment_6");
					put(grammarAccess.getSelectionAccess().getElementIDAssignment_1(), "rule__Selection__ElementIDAssignment_1");
					put(grammarAccess.getSelectionAccess().getLabelAssignment_2(), "rule__Selection__LabelAssignment_2");
					put(grammarAccess.getSelectionAccess().getPropertyAssignment_4(), "rule__Selection__PropertyAssignment_4");
					put(grammarAccess.getSelectionAccess().getSelectionItemsAssignment_6_0(), "rule__Selection__SelectionItemsAssignment_6_0");
					put(grammarAccess.getSelectionAccess().getSelectionItemsAssignment_6_1_1(), "rule__Selection__SelectionItemsAssignment_6_1_1");
					put(grammarAccess.getSelectionItemAccess().getValueAssignment_1_1(), "rule__SelectionItem__ValueAssignment_1_1");
					put(grammarAccess.getEnumerationLiteralItemAccess().getValueAssignment_1(), "rule__EnumerationLiteralItem__ValueAssignment_1");
					put(grammarAccess.getEnumerationLiteralItemAccess().getEnumerationLiteralAssignment_3(), "rule__EnumerationLiteralItem__EnumerationLiteralAssignment_3");
					put(grammarAccess.getLinkableElementAccess().getLinkAssignment_1_1(), "rule__LinkableElement__LinkAssignment_1_1");
					put(grammarAccess.getLinkAccess().getLabelAssignment_1(), "rule__Link__LabelAssignment_1");
					put(grammarAccess.getLinkAccess().getTargetViewAssignment_3(), "rule__Link__TargetViewAssignment_3");
					put(grammarAccess.getLayoutAccess().getAlignmentAssignment(), "rule__Layout__AlignmentAssignment");
					put(grammarAccess.getCompositeConditionAccess().getConditionIDAssignment_1(), "rule__CompositeCondition__ConditionIDAssignment_1");
					put(grammarAccess.getCompositeConditionAccess().getComposedConditionsAssignment_4_0(), "rule__CompositeCondition__ComposedConditionsAssignment_4_0");
					put(grammarAccess.getCompositeConditionAccess().getCompositionTypeAssignment_4_1(), "rule__CompositeCondition__CompositionTypeAssignment_4_1");
					put(grammarAccess.getCompositeConditionAccess().getComposedConditionsAssignment_4_2(), "rule__CompositeCondition__ComposedConditionsAssignment_4_2");
					put(grammarAccess.getCompositeConditionAccess().getTypeAssignment_7(), "rule__CompositeCondition__TypeAssignment_7");
					put(grammarAccess.getComparisonConditionAccess().getConditionIDAssignment_1(), "rule__ComparisonCondition__ConditionIDAssignment_1");
					put(grammarAccess.getComparisonConditionAccess().getPropertyAssignment_3(), "rule__ComparisonCondition__PropertyAssignment_3");
					put(grammarAccess.getComparisonConditionAccess().getComparisonTypeAssignment_4(), "rule__ComparisonCondition__ComparisonTypeAssignment_4");
					put(grammarAccess.getComparisonConditionAccess().getComparisonValueAssignment_5(), "rule__ComparisonCondition__ComparisonValueAssignment_5");
					put(grammarAccess.getComparisonConditionAccess().getTypeAssignment_7(), "rule__ComparisonCondition__TypeAssignment_7");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			at.ac.tuwien.big.views.view.ui.contentassist.antlr.internal.InternalViewParser typedParser = (at.ac.tuwien.big.views.view.ui.contentassist.antlr.internal.InternalViewParser) parser;
			typedParser.entryRuleViewModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ViewGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ViewGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
