/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.views.view.services.ViewGrammarAccess;

public class ViewParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ViewGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.views.view.parser.antlr.internal.InternalViewParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.views.view.parser.antlr.internal.InternalViewParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ViewModel";
	}
	
	public ViewGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ViewGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
