/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.views.view.ui.internal.ViewActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ViewExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ViewActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ViewActivator.getInstance().getInjector(ViewActivator.AT_AC_TUWIEN_BIG_VIEWS_VIEW_VIEW);
	}
	
}
