/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import at.ac.tuwien.big.views.view.nameprovider.ViewsNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ViewRuntimeModule extends at.ac.tuwien.big.views.view.AbstractViewRuntimeModule {
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return ViewsNameProvider.class;
	}

}