/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ViewStandaloneSetup extends ViewStandaloneSetupGenerated{

	public static void doSetup() {
		new ViewStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

