/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ViewUiModule extends at.ac.tuwien.big.views.view.ui.AbstractViewUiModule {
	public ViewUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
