/**
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view.ui.contentassist;

import at.ac.tuwien.big.views.view.ui.contentassist.AbstractViewProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ViewProposalProvider extends AbstractViewProposalProvider {
}
